<?php

namespace ContainerUVCzht1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PanierService' shared autowired service.
     *
     * @return \App\Service\PanierService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PanierService.php';

        return $container->privates['App\\Service\\PanierService'] = new \App\Service\PanierService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
