<?php

namespace ContainerIxL1BLH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatalogueControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CatalogueController' shared autowired service.
     *
     * @return \App\Controller\CatalogueController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CatalogueController.php';

        $container->services['App\\Controller\\CatalogueController'] = $instance = new \App\Controller\CatalogueController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->privates['App\\Repository\\PlatRepository'] ?? $container->load('getPlatRepositoryService')), ($container->privates['App\\Repository\\DetailRepository'] ?? $container->load('getDetailRepositoryService')), ($container->privates['App\\Repository\\CommandeRepository'] ?? $container->load('getCommandeRepositoryService')), ($container->privates['App\\Repository\\UtilisateurRepository'] ?? $container->load('getUtilisateurRepositoryService')), ($container->privates['App\\Service\\PanierService'] ?? $container->load('getPanierServiceService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\CatalogueController', $container));

        return $instance;
    }
}
