<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDf0SWp5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDf0SWp5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDf0SWp5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDf0SWp5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDf0SWp5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Df0SWp5',
    'container.build_id' => '728f2186',
    'container.build_time' => 1688042750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDf0SWp5');
