<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAISmJqO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAISmJqO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAISmJqO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAISmJqO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAISmJqO\App_KernelDevDebugContainer([
    'container.build_hash' => 'AISmJqO',
    'container.build_id' => '031f65c6',
    'container.build_time' => 1689081846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAISmJqO');
