<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3H6gana\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3H6gana/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3H6gana.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3H6gana\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3H6gana\App_KernelDevDebugContainer([
    'container.build_hash' => '3H6gana',
    'container.build_id' => '0f071bb0',
    'container.build_time' => 1688475975,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3H6gana');
